#pragma once

enum MSGTYPE{
	TASK_MSG_SETCONFIG=0x7ff,
	TASK_MSG_XMLMODIFY,
	TASK_MSG_CONTROLTASK,
	TASK_MSG_CONTROLALLTASK,
	TASK_MSG_QUERYTASK,
	TASK_MSG_THREADQUIT,
	TASK_MSG_APPEXIT,
	TASK_MSG_SCREENSAVER,
	TASK_MSG_UPDATE,
	TASK_MSG_LANGUAGE,
	TASK_MSG_POWER,
	TASK_MSG_SCANCFG,
	TASK_MSG_SETUP,

};

typedef struct tagTASKMSG{
	DWORD dwType;
	DWORD dwIndex;
	DWORD dwControl;
}TASKMSG,*LPTASKMSG;



