// dllmain.cpp : 定义 DLL 应用程序的入口点。
#include "stdafx.h"

#include "LuaVM.h"
#include "luahost.h"
USE_DEFAULT_DLL_MAIN;
BEGIN_CLIDMAP
	CLIDMAPENTRY_BEGIN
		CLIDMAPENTRY(CLSID_LuaVM,CLuaVM)
		CLIDMAPENTRY(CLSID_LuaHost,CLuaHost_S)
	CLIDMAPENTRY_END
END_CLIDMAP
DEFINE_ALL_EXPORTFUN