//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by 002.rc
//
#define IDR_MAINFRAME                   128
#define IDR_My002TYPE                   129
#define IDR_LANGUAGE_FILE               500
#define IDR_PNG_TOP_TOOLBAR             600
#define IDR_PNG_SHADOW                  601
#define IDR_PNG_EXAMPLE                 602
#define IDR_PNG_TEXTURE_BRICKS          610
#define IDR_PNG_TEXTURE_CANVAS_1        611
#define IDR_PNG_TEXTURE_CANVAS_2        612
#define IDR_PNG_TEXTURE_LEATHER         613
#define IDR_PNG_TEXTURE_SANDSTONE       614
#define IDR_PNG_TEXTURE_WEAVE           615
#define IDR_PNG_TEXTURE_MAT             616
#define IDR_PNG_TEXTURE_GRID            617
#define IDR_PNG_TEXTURE_DOT             618
#define IDC_SLIDER_1                    701
#define IDC_SLIDER_2                    702
#define IDC_SLIDER_3                    703
#define IDC_SLIDER_NAME_1               711
#define IDC_SLIDER_NAME_2               712
#define IDC_SLIDER_NAME_3               713
#define IDC_SLIDER_VALUE_1              721
#define IDC_SLIDER_VALUE_2              722
#define IDC_SLIDER_VALUE_3              723
#define IDD_EFFECT_OILPAINT             3100
#define IDD_EFFECT_NOISIFY              3101
#define IDD_EFFECT_COLOR_LEVEL          3102
#define IDD_EFFECT_COLOR_BALANCE        3103
#define IDD_EFFECT_EMBOSS               3104
#define IDD_EFFECT_3DGRID               3105
#define IDD_EFFECT_TEXTURE              3106
#define IDD_EFFECT_VIDEO                3107
#define IDD_EFFECT_LENSFLARE            3108
#define IDD_EFFECT_SUPERNOVA            3109
#define IDD_EFFECT_SHADOW               3110
#define IDD_OPEN_IMAGE                  3500
#define IDD_SAVE_IMAGE                  3501
#define IDD_IMAGE_RESIZE                3504
#define IDD_SINGLE_SLIDER               3521
#define IDD_TWO_SLIDER                  3522
#define IDD_THREE_SLIDER                3523
#define IDD_EFFECT_SHARP                3524
#define IDD_EFFECT_FILLGRID             3525
#define IDD_EFFECT_COLOR_TONE           3526
#define IDD_EFFECT_CUSTOM               3527
#define IDD_EFFECT_BLINDS               3528
#define IDD_EFFECT_RIPPLE               3529
#define IDD_EFFECT_LIB                  3535
#define ID_COLOR_BUTTON_CHANGE          20212
#define ID_EFFECT_DIALOG_POST_INIT      20223
#define ID_VIEW_ACTUAL                  20225
#define ID_VIEW_ZOOMIN_STEP             20227
#define ID_VIEW_ZOOMOUT_STEP            20228
#define ID_TOOL_EXPORT_ASCII            20236
#define ID_EFFECT_LIB_VISIBLE           20239
#define ID_VIEW_HOME                    20300
#define ID_EFFECT_FLIP                  26000
#define ID_EFFECT_MIRROR                26001
#define ID_EFFECT_EMBOSS                26002
#define ID_EFFECT_INVERT                26003
#define ID_EFFECT_MOSAIC                26004
#define ID_EFFECT_SPLASH                26008
#define ID_EFFECT_GRAYSCALE             26009
#define ID_EFFECT_THRESHOLD             26010
#define ID_EFFECT_OILPAINT              26012
#define ID_EFFECT_SOLARIZE              26013
#define ID_EFFECT_RIBBON                26015
#define ID_EFFECT_ADJUSTRGB             26017
#define ID_EFFECT_BRIGHTNESS            26018
#define ID_EFFECT_HUE                   26019
#define ID_EFFECT_GAMMA                 26020
#define ID_EFFECT_ROTATE90              26021
#define ID_EFFECT_ROTATE270             26023
#define ID_EFFECT_CANVAS_STRETCH        26026
#define ID_EFFECT_HALFTONE              26028
#define ID_EFFECT_BLURZOOM              26029
#define ID_EFFECT_BLURRADIAL            26030
#define ID_EFFECT_GLASSTILE             26031
#define ID_EFFECT_OLDPHOTO              26032
#define ID_EFFECT_SHIFT                 26034
#define ID_EFFECT_ILLUSION              26035
#define ID_EFFECT_BLUR_GAUSS            26036
#define ID_EFFECT_BLURMOTION            26037
#define ID_EFFECT_COLORLEVEL            26038
#define ID_EFFECT_AUTO_COLOR_LEVEL      26039
#define ID_EFFECT_COLORTONE             26040
#define ID_EFFECT_SHARP                 26042
#define ID_EFFECT_USMSHARP              26043
#define ID_EFFECT_COLORBALANCE          26044
#define ID_EFFECT_SOFTGLOW              26045
#define ID_EFFECT_WAVE                  26046
#define ID_EFFECT_CUSTOMFILTER          26047
#define ID_EFFECT_AUTO_CONTRAST         26048
#define ID_EFFECT_POSTERIZE             26049
#define ID_EFFECT_AUTO_COLORENHANCE     26050
#define ID_EFFECT_SMOOTHEDGE            26051
#define ID_EFFECT_DESPECKLE             26052
#define ID_EFFECT_NOISIFY               26053
#define ID_EFFECT_FILLGRID              26054
#define ID_EFFECT_BLINDS                26055
#define ID_EFFECT_TEXTURE               26056
#define ID_EFFECT_RAISEFRAME            26057
#define ID_EFFECT_3DGRID                26058
#define ID_EFFECT_RIPPLE                26059
#define ID_EFFECT_PENCILSKETCH          26060
#define ID_EFFECT_VIDEO                 26061
#define ID_EFFECT_LENSFLARE             26062
#define ID_EFFECT_SUPERNOVA             26063
#define ID_EFFECT_BULGE                 26064
#define ID_EFFECT_TWIST                 26065
#define ID_EFFECT_SOFT_PORTRAIT         26066
#define ID_EFFECT_DRAW_TEXT             26067
#define ID_EFFECT_SHADOW                26089
#define ID_EFFECT_END                   26090
#define ID_INDICATOR1                   30000
#define ID_INDICATOR2                   30001
#define ID_INDICATOR_ZOOM               30002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
