
#include "StdAfx.h"
#include "MSCDef.h"
#include "MsMsc.h"
#include "MsXMSCProxy.h"

USE_DEFAULT_DLL_MAIN
BEGIN_CLIDMAP
	CLIDMAPENTRY_BEGIN
		CLIDMAPENTRY_PROGID(CLSID_MsgBus, CMsMsc,_T("MsMsc"))
		CLIDMAPENTRY_PROGID(CLSID_MsgBusProxy, CMsXMSCProxy,_T("CLSID_MsgBusProxy.1"))
CLIDMAPENTRY_END
END_CLIDMAP_AND_EXPORTFUN